### ISSUE TITLE
Réflexions UX autour de la nouvelle vue edition

### ISSUE THREAD

**Issue by benjaminniess** [web-id-fr/cms-nova#6]
- Nom/ordre/contenu des tabs
- Ajout de composants à la volée (avec option pour les rendre réutilisables)
- Création de composants réutilisable en amont

**Comment by Ludovic-web-id** [comment]
Aucun problème pour aider à la réflexion !
Il faudrait qu'on en discute pour que je puisse être un peu plus au courant de ce qu'il ce trâme sur les évolutions :)

**Comment by benjaminniess** [comment]
Quelques pistes de réflexion que je vous commenterai à l'oral

![IMG_9123](https://github.com/web-id-fr/cms-nova/assets/1109647/17afed6d-b8ec-4754-9854-9b1f3260d214)

![IMG_9122](https://github.com/web-id-fr/cms-nova/assets/1109647/0906527d-1d24-4797-895d-d08d84ca7875)
