### ISSUE TITLE
Réflexions autour de la gestion des rôles et permissions

### ISSUE THREAD

**Issue by benjaminniess** [web-id-fr/cms-nova#8]
- A l'install de Laravel, les utilsateurs n'ont pas de rôle et il faut que ça s'adapte à tous les projets y compris ceux qui ont déjà leur système de role
- module à part ? middleware/policy dans publish à paramétrer / surcharger ?

**Comment by cedric-bidet** [comment]
On parle bien des droits en back-office ?
On n'a rien d'existant sur Nova pour ça ?

**Comment by benjaminniess** [comment]
Oui back office. On parle de en général comment on gère la logique autour des permissions. Est-ce qu'on ajoute une couche maison hookable ou est-ce qu'on arrive à gérer tout ça nativement avec les policies et middleware de laravel et de nova.
Mais dans une install fraiche de laravel il n'y a pas de table pour gérer les rôles et on ne veut pas non plus imposer un système
